name: qt5_osx
channels:
  - conda-forge
dependencies:
 - altgraph
 - appdirs
 - attrs
 - automat
 - babel
 - backports.functools_lru_cache
 - ca-certificates
 - certifi
 - clangdev
 - colorama
 - constantly
 - coverage
 - cython
 - h5py
 - hypothesis
 - lxml
 - macholib
 - mako
 - openssl
 - packaging
 - pycrypto
 - pyinstaller
 - pyqt
 - pytools
 - qt
 - qtconsole
 - sphinx=1.7.4
 - sphinxcontrib-websupport=1.0.1
 - tbb=2018_20171205
 - typing
 - service_identity
 - twisted
 - zope=1.0
 - matplotlib
 - scipy
 - hdf5
 - ipython=6
 - ipykernel=4.9
 - jupyter
 - pytest
 - testpath
 - numpy
 - pyopencl
 - pip:
   - pytools
   - periodictable
   - bumps
   - xhtml2pdf
   - qt5reactor

