name: qt5_win
channels:
  - conda-forge
dependencies:
  - matplotlib=3.2.1
  - scipy=1.3.1
  - hdf5
  - h5py=2.10.0
  - ipython=7.15.0
  - ipykernel=5.3.0
  - jupyter
  - twisted=20.3.0
  - lxml=4.5.1
  - sphinx=3.1.1
  - cython=0.29.20
  - pytest=5.4.3
  - mako=1.1.0
  - pyinstaller
  - pyopencl
  - testpath=0.4.4
  - numba=0.48.0
  - numpy=1.18.5
  - pip:
    - pytools
    - periodictable==1.5.2
    - bumps==0.7.16
    - xhtml2pdf==0.2.4
    - qt5reactor==0.6.1
    - tinycc==1.1


# QT: 5.12.5
# PyQT: 5:12.3
