about: {home: 'http://www.reflectometry.org/danse/software.html', license: UNKNOWN,
  summary: Data fitting with bayesian uncertainty analysis}
package: {name: bumps, version: 0.7.5.3}
requirements:
  build:
    - python
    - setuptools
    - six
  run:
    - python
    - six
source:
  fn: bumps-0.7.5.3.tar.gz
  md5: f17b41412c3c8ad6432a42e42cb926d5
  url: https://pypi.python.org/packages/source/b/bumps/bumps-0.7.5.3.tar.gz
test:
  imports:
    - bumps
    - bumps.dream
    - bumps.gui
    - bumps.gui.resources
    - bumps.mystic
    - bumps.mystic.examples
    - bumps.mystic.optimizer
  requires:
    - numpy
    - scipy
    - matplotlib
