about: {home: 'http://github.com/xmlrunner/unittest-xml-reporting/tree/master/', license: BSD
    License, summary: unittest-based test runner with Ant/JUnit like XML reporting.}
build:
  features:
    - I dunno.  The ability to actually work would be nice feature of this recipe.
package: {name: unittest-xml-reporting, version: 1.10.0}
requirements:
  build:
    - python
    - setuptools
    - six
  run:
    - python
    - six
source:
  fn: unittest-xml-reporting-1.10.0.tar.gz
  md5: f0d04be2b9bff5b744677b576c326620
  url: https://pypi.python.org/packages/source/u/unittest-xml-reporting/unittest-xml-reporting-1.10.0.tar.gz
test:
  imports:
    - xmlrunner
    - xmlrunner.extra
    - xmlrunner.tests
