about: {home: 'http://www.reflectometry.org/danse/elements.html', license: public
    domain, summary: Extensible periodic table of the elements}
package: {name: periodictable, version: 1.4.1}
requirements:
  build:
    - python
    - setuptools
    - pyparsing
    - numpy
  run:
    - python
    - pyparsing
    - numpy
source:
  fn: periodictable-1.4.1.tar.gz
  md5: 7246b63cc0b6b1be6e86b6616f9e866e
  url: https://pypi.python.org/packages/source/p/periodictable/periodictable-1.4.1.tar.gz
test:
  imports:
    - periodictable
